version = 1

exclude_patterns = [
  "index.html",
  "0e60031d/index.php"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "prettier"
enabled = true